### ISSUE TITLE
1.20.4 doesn't compile on ghc 8.0.1rc2

### ISSUE THREAD

**Issue by GeorgeCo** [ekmett/linear#99]
Sorry if this is a known issue. Currently it seems that the latest version that can be installed with 8.0.1rc2 is linear 0.6.1:

`bash-3.2$ cabal install -j5 linear
Resolving dependencies...
All the requested packages are already installed:
linear-0.6.1
Use --reinstall if you want to reinstall anyway.`

Using allow-newer shows that 1.20.4 doesn't compile with 8.0.1rc2:

` cabal install -j5 linear --allow-newer
Resolving dependencies...
Configuring linear-1.20.4...
Building linear-1.20.4...
Failed to install linear-1.20.4
Build log ( /Users/gcolpitts/.cabal/logs/linear-1.20.4.log ):
[1 of 1] Compiling Main             ( /var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-31406/linear-1.20.4/dist/setup/setup.hs, /var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-31406/linear-1.20.4/dist/setup/Main.o )
Linking /var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-31406/linear-1.20.4/dist/setup/setup ...
Configuring linear-1.20.4...
Building linear-1.20.4...
Preprocessing library linear-1.20.4...
[ 1 of 22] Compiling Linear.Instances ( src/Linear/Instances.hs, dist/build/Linear/Instances.o )
[ 2 of 22] Compiling Linear.Vector    ( src/Linear/Vector.hs, dist/build/Linear/Vector.o )
[ 3 of 22] Compiling Linear.Epsilon   ( src/Linear/Epsilon.hs, dist/build/Linear/Epsilon.o )
[ 4 of 22] Compiling Linear.Metric    ( src/Linear/Metric.hs, dist/build/Linear/Metric.o )
[ 5 of 22] Compiling Linear.V0        ( src/Linear/V0.hs, dist/build/Linear/V0.o )

src/Linear/V0.hs:318:25: error:
    ‘eq1’ is not a (visible) method of class ‘Eq1’

src/Linear/V0.hs:319:25: error:
    ‘compare1’ is not a (visible) method of class ‘Ord1’

src/Linear/V0.hs:320:25: error:
    ‘showsPrec1’ is not a (visible) method of class ‘Show1’

src/Linear/V0.hs:321:25: error:
    ‘readsPrec1’ is not a (visible) method of class ‘Read1’
cabal: Error: some packages failed to install:
linear-1.20.4 failed during the building phase. The exception was:
ExitFailure 1
bash-3.2$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.0.20160204`

**Comment by GeorgeCo** [comment]
Sorry I believe this is a duplicate of #97
