### ISSUE TITLE
Does not build with `vector-0.13.*`

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/linear#172]
If I try to raise `linear`'s upper version bounds on `vector` to allow building with `vector-0.13.*`, it will fail to compile:

```
[ 7 of 22] Compiling Linear.V         ( src/Linear/V.hs, /home/ryanglscott/Documents/Hacking/Haskell/ci-maintenance/checkout/ekmett/linear/dist-newstyle/build/x86_64-linux/ghc-9.2.3/linear-1.21.9/build/Linear/V.o, /home/ryanglscott/Documents/Hacking/Haskell/ci-maintenance/checkout/ekmett/linear/dist-newstyle/build/x86_64-linux/ghc-9.2.3/linear-1.21.9/build/Linear/V.dyn_o )

src/Linear/V.hs:547:70: error:
    • Couldn't match expected type: GHC.ST.ST s ()
                  with actual type: vector-stream-0.1.0.0:Data.Stream.Monadic.Box ()
    • In the expression: go v0 vn0 d0 (d0 * i) 0
      In the expression: let d0 = V.length vn0 in go v0 vn0 d0 (d0 * i) 0
      In an equation for ‘M.basicUnsafeWrite’:
          M.basicUnsafeWrite (MV_VN _ v0) i (V vn0)
            = let d0 = V.length vn0 in go v0 vn0 d0 (d0 * i) 0
            where
                go v vn d o j
                  | j >= d = return ()
                  | otherwise
                  = do a <- G.basicUnsafeIndexM vn j
                       ....
    • Relevant bindings include
        v0 :: U.MVector s a (bound at src/Linear/V.hs:547:29)
        basicUnsafeWrite :: U.MVector s (V n a)
                            -> Int -> V n a -> GHC.ST.ST s ()
          (bound at src/Linear/V.hs:547:3)
    |
547 |   basicUnsafeWrite (MV_VN _ v0) i (V vn0) = let d0 = V.length vn0 in go v0 vn0 d0 (d0*i) 0
    |                                                                      ^^^^^^^^^^^^^^^^^^^^^

src/Linear/V.hs:553:9: error:
    • Couldn't match type ‘GHC.ST.ST s1’
                     with ‘vector-stream-0.1.0.0:Data.Stream.Monadic.Box’
      Expected: vector-stream-0.1.0.0:Data.Stream.Monadic.Box ()
        Actual: GHC.ST.ST s1 ()
    • In a stmt of a 'do' block: M.basicUnsafeWrite v o a
      In the expression:
        do a <- G.basicUnsafeIndexM vn j
           M.basicUnsafeWrite v o a
           go v vn d (o + 1) (j + 1)
      In an equation for ‘go’:
          go v vn d o j
            | j >= d = return ()
            | otherwise
            = do a <- G.basicUnsafeIndexM vn j
                 M.basicUnsafeWrite v o a
                 go v vn d (o + 1) (j + 1)
    • Relevant bindings include
        v :: v s1 a1 (bound at src/Linear/V.hs:549:8)
        go :: v s1 a1
              -> v1 a1
              -> Int
              -> Int
              -> Int
              -> vector-stream-0.1.0.0:Data.Stream.Monadic.Box ()
          (bound at src/Linear/V.hs:549:5)
    |
553 |         M.basicUnsafeWrite v o a
    |         ^^^^^^^^^^^^^^^^^^^^^^^^
```
